### ISSUE TITLE
Recover secret: white screen if 2 of 3 guardians accepted request

### ISSUE THREAD

**Issue by Alusar** [alexandrim0/keyper#1]
build 2.0.0.1
honor 7a - android 8.1.0
samsung s10e - android 12
poco m4 pro - android 12

Steps to reproduce:

1. Create Vault (3), add guardians
2. Create a Secret
3. Press "Recover my Secret"
4. 2 of 3 guardians pressed Accept
5. Press "Access Secret"
6. Enter pincode

Actual result: 
white screen on owner app, when trying to recover secret 

<details><summary>Example</summary>

![image](https://user-images.githubusercontent.com/58986565/197785060-8d1276fe-33b6-4562-821a-8768d9befcbf.png)

</details>

Expected Result:
screen opens with access to the secret

**Comment by alexandrim0** [comment]
fixed with commit [1831c83](https://github.com/alexandrim0/keyper/commit/1831c837ad3de6c1a89a2e952a7d351f5ec61eaf)
