### ISSUE TITLE
guardian can accept a request when owner has canceled pending response (add to vault)

### ISSUE THREAD

**Issue by Alusar** [alexandrim0/keyper#10]
2.0.2

steps:
1. as owner, create a vault
2. as owner, scan guardian's QR-code, wait for response
3. as owner, press cansel (cross in upper right corner)
4. as guard, press "approve" on incoming request

expected result: 
if owner cancelled waiting for response, guardian can't approve incoming request

actual result: 
guardian can approve incoming request
gets saved shard

**Comment by alexandrim0** [comment]
It is a part of protocol design and does not lead to data loss or miss functional.
In this case, guardian which already accepted request will keep garbage data after canceling request.
Wont fix.
