### ISSUE TITLE
guardian name not updating on home screen after change

### ISSUE THREAD

**Issue by Alusar** [alexandrim0/keyper#2]
android 12
version 2.0.0

steps:
1. launch app
2. open "settings", change name, press "proceed"
3. close settings tab

expected result:
name is updated on main screen

actual result:
name is not updated on main screen after changes
updated only after switching to another screen and returning back to the main

<details>

 ![image](https://user-images.githubusercontent.com/58986565/229141544-93242140-2d54-4d29-99af-47bab91e5a0e.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/58986565/229142348-9cffdc06-f3a5-4bdb-ae9f-753a05743bf0.png)

</details>

**Comment by alexandrim0** [comment]
fixed 2.0.1
