### ISSUE TITLE
popup not closing after remove vault

### ISSUE THREAD

**Issue by Alusar** [alexandrim0/keyper#3]
android 12
version 2.0.0

steps:
1. launch app
2. create a new vault
3. tap on vault, open action-menu, choise "remove the vault"

expected result:
after removing, pupup window clossing and returns to vault creation window 

actual result:
after removing, pupup window not clossing 

<details>

![image](https://user-images.githubusercontent.com/58986565/229158556-b0c6904b-11ca-4373-9662-5e75df6abfab.png)

</details>

**Comment by alexandrim0** [comment]
fix 2.0.1
