### ISSUE TITLE
first adding a guardian - requests don't come before switching between screens

### ISSUE THREAD

**Issue by Alusar** [alexandrim0/keyper#4]
ver 2.0.0
android 12 (owner) -> android 12 (guardian, fist instalation) 

steps:
1. (owner) create a new vault, press "add a guardian"
2. scan QR-code on guardian phone

expected result:
owner waiting for request confirmation
guardian receives a request for adding to new vault

actual result:
owner waiting for request confirmation
guardian does not receive a request (need to switch to the "messages" or "Shards" window to receive)

<details>

https://user-images.githubusercontent.com/58986565/229179849-cf42e5cf-9196-44d0-bc71-d195b45ccf3c.mp4

</details>

**Comment by alexandrim0** [comment]
fixed 2.0.1
