### ISSUE TITLE
passcode window freezes when pressing "show" a secret

### ISSUE THREAD

**Issue by Alusar** [alexandrim0/keyper#6]
ver 2.0.1
android 12 

steps:
1. create vault, add guardians
2. split secret
3. press "show" on secret
4. enter passcode

expected result:
after entering the passcode, window closes
window with secret show up

actual result:
after entering the passcode, window freezes 
closes only after clicking "cancel"

<details>

![image](https://user-images.githubusercontent.com/58986565/229336515-b76eeb9f-0ccb-4a59-b471-5d94a7d21870.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/58986565/229336462-c0644777-dc0f-4328-a6ff-0b92f4cdfd7b.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/58986565/229336546-3a2ad2a1-db1e-4447-9fc1-3d50beca577d.png)

</details>

**Comment by alexandrim0** [comment]
fixed 2.0.2
