### ISSUE TITLE
IOS: biometric authentication not accepted 

### ISSUE THREAD

**Issue by Alusar** [alexandrim0/keyper#7]
ver 2.0.0
ios 16.3

steps: 
1. open app 
2. use biometric authentication (touchid\bio)

expected result: 
after using biometric authentication (face|touchid), passcode window closing
user gets access to functionality of application

actual result:
passcode window closes and reopens

https://user-images.githubusercontent.com/58986565/229492939-4cd5ff3d-7960-41ad-b9b3-5ac672f26a0f.mov

**Comment by alexandrim0** [comment]
should check on 2.0.2

**Comment by alexandrim0** [comment]
may be https://github.com/flutter/flutter/issues/65328

**Comment by alexandrim0** [comment]
fixed with 2.0.2
