### ISSUE TITLE
10.4.1 "secret screen" doesnt appear after aproving 1st and 3rd guardian (2nd rejected)

### ISSUE THREAD

**Issue by Alusar** [alexandrim0/keyper#9]
ver 2.0.1
android 12

steps:
1. create a vault, add guardians, split secret
2. as owner open vault, chooise secret, press "recover my secret"
3. as guardian 1st approve recovery request 
4. as guardian 2nd reject request 
5. as guardian 3rd approve recovery request 

expected result: 
opens window with secret (figma 10.4.1)

actual result:
secret window not opening
shows loader for aprove by 3rd guardian
<details>

![image](https://user-images.githubusercontent.com/58986565/229532640-8a777f48-edbf-4762-bb32-5a07890b408f.png)

</details>

**Also, same behavior for group of 5 (including with flag "Keep one shard on my device")**

**Comment by alexandrim0** [comment]
fixed with 2.0.2
